name: qgrid-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyterlab
  - qgrid
  - matplotlib>=2.1.1
  - pandas>=0.25.1
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - cufflinks>=0.17.0
  - pyopenssl=19.0.0=py37_0
  - nodejs
  - pyOpenSSL==19.0.0
  - ipywidgets==7.5.1
  - plotly

